version: '3.5'
networks:
  book-test-network:
    name: book-test-network
services:
    book-database:
        image: "microsoft/mssql-server-linux:latest"
        container_name: book-database
        environment:
            SA_PASSWORD: "Book#123"
            ACCEPT_EULA: Y
        ports:
            - "2433:1433"
        networks:
          - "book-test-network"
    book-api:
        image: book-api
        container_name: book-api-container
        build:
          context: ./Book
          dockerfile: Dockerfile
        ports:
        - "5000:5000"
        networks:
          - "book-test-network"
        restart: on-failure
        depends_on:
          - book-database
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
      